### ISSUE TITLE
stopped working on tensorflow 2.16 due to estimator retirement

### ISSUE THREAD

**Issue by weisun76** [aime-team/tf2-benchmarks#3]
root@9e80f42b836c:/mnt/DL/tf2-benchmarks# python tf2-benchmarks.py --model resnet50 --xla --batch_size 64 --num_gpus 1
Traceback (most recent call last):
  File "/mnt/DL/tf2-benchmarks/tf2-benchmarks.py", line 37, in <module>
    from utils.flags import core as flags_core
  File "/mnt/DL/tf2-benchmarks/utils/flags/core.py", line 30, in <module>
    from utils.flags import _base
  File "/mnt/DL/tf2-benchmarks/utils/flags/_base.py", line 25, in <module>
    from utils.logs import hooks_helper
  File "/mnt/DL/tf2-benchmarks/utils/logs/hooks_helper.py", line 29, in <module>
    from utils.logs import hooks
  File "/mnt/DL/tf2-benchmarks/utils/logs/hooks.py", line 28, in <module>
    class ExamplesPerSecondHook(tf.estimator.SessionRunHook):
AttributeError: module 'tensorflow' has no attribute 'estimator'
